os: Visual Studio 2017

environment:
  node_pre_gyp_accessKeyId:
    secure: IAy8goREssK8/Lxj7sGTBTPuVYq+UQOjg1BloxR7VaA=
  node_pre_gyp_secretAccessKey:
    secure: Hceud2JsCah/e7u67V+S9io4SEiHqAtZ/XVmDNmEBFniOSYXUzVPKzdKTRKHWlOO
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13

platform:
  - x64
  - x86

branches:
  only:
    - master

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm config get
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - npm install
  - node_modules\.bin\node-pre-gyp package publish

build: off
test: off
deploy: off
